apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672  # Port for messaging
        - containerPort: 15672 # Port for management console
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - port: 15672
    targetPort: 15672
    name: management # Add a name for the port (e.g., "management" for the UI)
  selector:
    app: rabbitmq
